services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis_data:/data

  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
    entrypoint: |
      /bin/sh -c '
        while ! mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} >/dev/null 2>&1; do
          echo "waiting for minio..."; sleep 2;
        done
        mc mb -p local/${MINIO_BUCKET} || true
        mc anonymous set download local/${MINIO_BUCKET} || true
      '

  web:
    build: ./infra/web
    env_file: .env
    environment:
      IN_DOCKER: "1"
      DJANGO_DEBUG: "1"
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      create-bucket:
        condition: service_completed_successfully
  
  # ======================================================================================
  # |-                              -| GRAFANA SERVICES |-                              -|
  # ======================================================================================

  # --------------------------------------
  #   TELEMETRY COLLECTOR & DISTRIBUTOR  |
  # --------------------------------------
  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./infra/telemetry/config/config.alloy:/etc/alloy/config.alloy
    depends_on:
      - loki
      - tempo
      - prometheus
    ports:
      # The Alloy interface and receivers can't be password-protected so these ports
      # probably shouldn't be exposed like this (i.e. bound to `0.0.0.0:[port]`) in a
      # "real" instance of this service (without properly configuring e.g. auth headers).
      #
      # In whatever case, the interface at http://localhost:12345 can be used to view and
      # debug Alloy OTEL ingress and distribution.
      - "12345:12345"                       # alloy interface
      - "4317:4317"                         # otlp grpc receiver
      - "4318:4318"                         # otlp http receiver

  # ------------------------------
  #        TRACES RECEIVER       |
  # ------------------------------
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./infra/telemetry/config/tempo.yml:/etc/tempo.yml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
  
  # -----------------------------
  #         LOGS RECEIVER       |
  # -----------------------------
  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki.yml"]
    volumes:
      - ./infra/telemetry/config/loki.yml:/etc/loki.yml
      - loki_data:/loki
    ports:
      - "3100:3100"

  # ------------------------------
  #        METRICS RECEIVER      |
  # ------------------------------
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./infra/telemetry/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
   
  # ------------------------------
  #       GRAFANA DASHBOARD      | 
  # ------------------------------
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      # Enables passwordless administration (!)
      # 
      # Note that similar to the Alloy config, you would want something more 
      # like the following in a proper deployment:
      #
      # ```
      # environment:
      #   - GF_USERS_ALLOW_SIGN_UP=false
      #   - GF_AUTH_ANONYMOUS_ENABLED=false
      #   - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      #   - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      # ```
      #
      # (where `GRAFANA_ADMIN_USER` and `GRAFANA_ADMIN_PASSWORD` are defined
      # as environment variables).
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

      # Pass environment variables to the container so they can be used in 
      # `datasources.yml`
      - GF_PG_READER_USER=${GF_PG_READER_USER}
      - GF_PG_READER_PASS=${GF_PG_READER_PASS}
      - POSTGRES_DB=${POSTGRES_DB}

      # Plugin auto-installation
      - GF_PLUGINS_PREINSTALL_SYNC=redis-datasource

    volumes:
      - ./infra/telemetry/config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_data:/var/lib/grafana
    depends_on:
      - db
      - redis
      - loki
      - tempo
      - prometheus

volumes:
  db_data:
  redis_data:
  minio_data:

  grafana_data:
  prom_data:
  loki_data:
  tempo_data:

