# Generated by Django 5.2.7 on 2025-10-06 21:22

import core.models
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('mode', models.CharField(choices=[('EXPLORATION', 'Exploration'), ('MINING', 'Mining')], default='EXPLORATION')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('mode__in', ['EXPLORATION', 'MINING'])), name='valid_organisation_mode')],
            },
            bases=(core.models.ChoiceValidationMixin, core.models.AutoCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('mode', models.CharField(choices=[('PROJECT', 'Project'), ('OPERATION', 'Operation')], default='PROJECT')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('commodity', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
            ],
            bases=(core.models.ChoiceValidationMixin, core.models.AutoCleanMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Drillhole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='docs/')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=list), size=None)),
                ('timestamp', models.DateField(null=True)),
                ('doc_type', models.CharField(blank=True, max_length=64)),
                ('confidentiality', models.CharField(default='internal', max_length=64)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.process')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process')),
            ],
        ),
        migrations.CreateModel(
            name='Tenement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organisation')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.process')),
            ],
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['PROJECT', 'OPERATION'])), name='valid_process_mode'),
        ),
    ]
