# Generated by Django 5.2.7 on 2025-10-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_created_at_alter_document_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='document',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organisation'),
        ),
    ]
