# Generated by Django 5.2.7 on 2025-10-13 09:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillhole',
            name='azimuth',
            field=models.FloatField(blank=True, help_text='Bearing (0-360 degrees)', null=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='collar_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='depth',
            field=models.FloatField(blank=True, help_text='Total depth in meters', null=True),
        ),
        migrations.AddField(
            model_name='drillhole',
            name='dip',
            field=models.FloatField(blank=True, help_text='Dip angle (-90 to 90 degrees, negative = downward)', null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='tenement',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
