# Generated by Django 5.2.12 on 2026-03-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_drillhole_azimuth_drillhole_collar_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('doc_type', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.document')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.process')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['process'], name='core_docume_process_f5b3f3_idx'), models.Index(fields=['doc_type'], name='core_docume_doc_typ_499972_idx'), models.Index(fields=['timestamp'], name='core_docume_timesta_294cd6_idx')],
            },
        ),
    ]
