# Generated by Django 5.2.7 on 2026-04-05 07:11

import environ
from django.db import migrations

env = environ.Env()

GF_PG_READER_USER = env("GF_PG_READER_USER") or "grafana"
GF_PG_READER_PASS = env("GF_PG_READER_PASS") or "grafana"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_savedreport"),
    ]

    operations = [
        migrations.RunSQL(
            sql=f"""
            CREATE USER {GF_PG_READER_USER} WITH PASSWORD '{GF_PG_READER_USER}';
            GRANT SELECT ON ALL TABLES IN SCHEMA public TO {GF_PG_READER_USER};

            ALTER DEFAULT PRIVILEGES IN SCHEMA public 
            GRANT SELECT ON TABLES TO {GF_PG_READER_USER};
            """,
            reverse_sql=f"""
            REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM {GF_PG_READER_USER};
            REVOKE ALL PRIVILEGES ON SCHEMA public FROM {GF_PG_READER_USER};

            ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
            REVOKE ALL ON TABLES FROM {GF_PG_READER_USER};

            DROP USER {GF_PG_READER_USER};
            """,
        )
    ]
