# Generated by Django 5.2.12 on 2026-03-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_savedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='analysis_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
