# Generated by Django 5.2.7 on 2026-05-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260405_0843'),
        ('core', '0014_document_search_tsv'),
    ]

    operations = [
    ]
