# Generated by Django 5.2.12 on 2026-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20260504_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='source_documents',
            field=models.ManyToManyField(blank=True, help_text='Documents used as sources when generating this report.', related_name='generated_reports', to='core.document'),
        ),
    ]
