--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg110+2)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg110+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: approval_workflows; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.approval_workflows (
    id bigint NOT NULL,
    object_id uuid NOT NULL,
    workflow_type character varying(16) NOT NULL,
    status character varying(16) NOT NULL,
    submission_notes text NOT NULL,
    approval_notes text NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    approved_by_id integer,
    content_type_id integer NOT NULL,
    submitted_by_id integer NOT NULL
);


ALTER TABLE public.approval_workflows OWNER TO postgres;

--
-- Name: approval_workflows_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.approval_workflows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_workflows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(16) NOT NULL,
    object_id uuid NOT NULL,
    description text NOT NULL,
    ip_address inet,
    user_agent text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    content_type_id integer NOT NULL,
    user_id integer
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id integer NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id integer NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_document (
    id uuid NOT NULL,
    title character varying(64) NOT NULL,
    file character varying(100) NOT NULL,
    tags integer[] NOT NULL,
    "timestamp" date,
    doc_type character varying(64) NOT NULL,
    confidentiality character varying(64) NOT NULL,
    checksum_sha256 character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer,
    organisation_id uuid,
    process_id uuid
);


ALTER TABLE public.core_document OWNER TO postgres;

--
-- Name: core_drillhole; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_drillhole (
    id uuid NOT NULL,
    name character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organisation_id uuid NOT NULL,
    process_id uuid NOT NULL,
    azimuth double precision,
    collar_location public.geometry(Point,4326),
    depth double precision,
    dip double precision
);


ALTER TABLE public.core_drillhole OWNER TO postgres;

--
-- Name: core_organisation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_organisation (
    id uuid NOT NULL,
    name character varying(32),
    mode character varying NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT valid_organisation_mode CHECK (((mode)::text = ANY ((ARRAY['EXPLORATION'::character varying, 'MINING'::character varying])::text[])))
);


ALTER TABLE public.core_organisation OWNER TO postgres;

--
-- Name: core_process; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_process (
    id uuid NOT NULL,
    name character varying(64),
    mode character varying NOT NULL,
    geom public.geometry(MultiPolygon,4326),
    commodity character varying(64),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organisation_id uuid,
    CONSTRAINT valid_process_mode CHECK (((mode)::text = ANY ((ARRAY['PROJECT'::character varying, 'OPERATION'::character varying])::text[])))
);


ALTER TABLE public.core_process OWNER TO postgres;

--
-- Name: core_prospect; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_prospect (
    id uuid NOT NULL,
    name character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organisation_id uuid NOT NULL,
    process_id uuid NOT NULL,
    geom public.geometry(Point,4326)
);


ALTER TABLE public.core_prospect OWNER TO postgres;

--
-- Name: core_tenement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_tenement (
    id uuid NOT NULL,
    name character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organisation_id uuid NOT NULL,
    process_id uuid NOT NULL,
    geom public.geometry(MultiPolygon,4326)
);


ALTER TABLE public.core_tenement OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: document_views; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.document_views (
    id bigint NOT NULL,
    viewed_at timestamp with time zone NOT NULL,
    ip_address inet,
    document_id uuid NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.document_views OWNER TO postgres;

--
-- Name: document_views_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.document_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    role character varying(32) NOT NULL,
    clearance_level character varying(32) NOT NULL,
    department character varying(64) NOT NULL,
    phone character varying(32) NOT NULL,
    employee_id character varying(32),
    can_approve_jorc boolean NOT NULL,
    can_approve_valmin boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    organisation_id uuid,
    user_id integer NOT NULL
);


ALTER TABLE public.user_profiles OWNER TO postgres;

--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: approval_workflows approval_workflows_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval_workflows
    ADD CONSTRAINT approval_workflows_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_document core_document_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_document
    ADD CONSTRAINT core_document_pkey PRIMARY KEY (id);


--
-- Name: core_drillhole core_drillhole_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_drillhole
    ADD CONSTRAINT core_drillhole_pkey PRIMARY KEY (id);


--
-- Name: core_organisation core_organisation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_organisation
    ADD CONSTRAINT core_organisation_pkey PRIMARY KEY (id);


--
-- Name: core_process core_process_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_process
    ADD CONSTRAINT core_process_pkey PRIMARY KEY (id);


--
-- Name: core_prospect core_prospect_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_prospect
    ADD CONSTRAINT core_prospect_pkey PRIMARY KEY (id);


--
-- Name: core_tenement core_tenement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_tenement
    ADD CONSTRAINT core_tenement_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: document_views document_views_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_views
    ADD CONSTRAINT document_views_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_employee_id_key UNIQUE (employee_id);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);


--
-- Name: approval_workflows_approved_by_id_19fe0d61; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX approval_workflows_approved_by_id_19fe0d61 ON public.approval_workflows USING btree (approved_by_id);


--
-- Name: approval_workflows_content_type_id_08e9f046; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX approval_workflows_content_type_id_08e9f046 ON public.approval_workflows USING btree (content_type_id);


--
-- Name: approval_workflows_submitted_by_id_4596c10b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX approval_workflows_submitted_by_id_4596c10b ON public.approval_workflows USING btree (submitted_by_id);


--
-- Name: audit_logs_content_b0ef47_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_content_b0ef47_idx ON public.audit_logs USING btree (content_type_id, object_id);


--
-- Name: audit_logs_content_type_id_47a353b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_content_type_id_47a353b2 ON public.audit_logs USING btree (content_type_id);


--
-- Name: audit_logs_timesta_423be6_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_timesta_423be6_idx ON public.audit_logs USING btree ("timestamp");


--
-- Name: audit_logs_user_id_752b0e2b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_user_id_752b0e2b ON public.audit_logs USING btree (user_id);


--
-- Name: audit_logs_user_id_d685f3_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_user_id_d685f3_idx ON public.audit_logs USING btree (user_id, action);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_document_checksum_sha256_4a11a755; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_document_checksum_sha256_4a11a755 ON public.core_document USING btree (checksum_sha256);


--
-- Name: core_document_checksum_sha256_4a11a755_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_document_checksum_sha256_4a11a755_like ON public.core_document USING btree (checksum_sha256 varchar_pattern_ops);


--
-- Name: core_document_created_by_id_27ee15cc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_document_created_by_id_27ee15cc ON public.core_document USING btree (created_by_id);


--
-- Name: core_document_organisation_id_8df8c969; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_document_organisation_id_8df8c969 ON public.core_document USING btree (organisation_id);


--
-- Name: core_document_process_id_c0ddf028; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_document_process_id_c0ddf028 ON public.core_document USING btree (process_id);


--
-- Name: core_drillhole_collar_location_aa25ffca_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_drillhole_collar_location_aa25ffca_id ON public.core_drillhole USING gist (collar_location);


--
-- Name: core_drillhole_organisation_id_498b2b65; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_drillhole_organisation_id_498b2b65 ON public.core_drillhole USING btree (organisation_id);


--
-- Name: core_drillhole_process_id_e513b27c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_drillhole_process_id_e513b27c ON public.core_drillhole USING btree (process_id);


--
-- Name: core_process_geom_3cd3977f_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_process_geom_3cd3977f_id ON public.core_process USING gist (geom);


--
-- Name: core_process_organisation_id_b3539040; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_process_organisation_id_b3539040 ON public.core_process USING btree (organisation_id);


--
-- Name: core_prospect_geom_197a5182_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_prospect_geom_197a5182_id ON public.core_prospect USING gist (geom);


--
-- Name: core_prospect_organisation_id_2033ec0d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_prospect_organisation_id_2033ec0d ON public.core_prospect USING btree (organisation_id);


--
-- Name: core_prospect_process_id_6be9fa7e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_prospect_process_id_6be9fa7e ON public.core_prospect USING btree (process_id);


--
-- Name: core_tenement_geom_e41e471b_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_tenement_geom_e41e471b_id ON public.core_tenement USING gist (geom);


--
-- Name: core_tenement_organisation_id_a6e9c1eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_tenement_organisation_id_a6e9c1eb ON public.core_tenement USING btree (organisation_id);


--
-- Name: core_tenement_process_id_e9ee895b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_tenement_process_id_e9ee895b ON public.core_tenement USING btree (process_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: document_vi_documen_dcb332_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX document_vi_documen_dcb332_idx ON public.document_views USING btree (document_id, user_id);


--
-- Name: document_vi_viewed__659188_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX document_vi_viewed__659188_idx ON public.document_views USING btree (viewed_at);


--
-- Name: document_views_document_id_151c5e8f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX document_views_document_id_151c5e8f ON public.document_views USING btree (document_id);


--
-- Name: document_views_user_id_8746d44f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX document_views_user_id_8746d44f ON public.document_views USING btree (user_id);


--
-- Name: user_profiles_employee_id_e5c34f59_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_profiles_employee_id_e5c34f59_like ON public.user_profiles USING btree (employee_id varchar_pattern_ops);


--
-- Name: user_profiles_organisation_id_6ad56cce; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_profiles_organisation_id_6ad56cce ON public.user_profiles USING btree (organisation_id);


--
-- Name: approval_workflows approval_workflows_approved_by_id_19fe0d61_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval_workflows
    ADD CONSTRAINT approval_workflows_approved_by_id_19fe0d61_fk_auth_user_id FOREIGN KEY (approved_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: approval_workflows approval_workflows_content_type_id_08e9f046_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval_workflows
    ADD CONSTRAINT approval_workflows_content_type_id_08e9f046_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: approval_workflows approval_workflows_submitted_by_id_4596c10b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval_workflows
    ADD CONSTRAINT approval_workflows_submitted_by_id_4596c10b_fk_auth_user_id FOREIGN KEY (submitted_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_logs audit_logs_content_type_id_47a353b2_fk_django_content_type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_content_type_id_47a353b2_fk_django_content_type_id FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_logs audit_logs_user_id_752b0e2b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_752b0e2b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_document core_document_created_by_id_27ee15cc_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_document
    ADD CONSTRAINT core_document_created_by_id_27ee15cc_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_document core_document_organisation_id_8df8c969_fk_core_organisation_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_document
    ADD CONSTRAINT core_document_organisation_id_8df8c969_fk_core_organisation_id FOREIGN KEY (organisation_id) REFERENCES public.core_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_document core_document_process_id_c0ddf028_fk_core_process_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_document
    ADD CONSTRAINT core_document_process_id_c0ddf028_fk_core_process_id FOREIGN KEY (process_id) REFERENCES public.core_process(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_drillhole core_drillhole_organisation_id_498b2b65_fk_core_organisation_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_drillhole
    ADD CONSTRAINT core_drillhole_organisation_id_498b2b65_fk_core_organisation_id FOREIGN KEY (organisation_id) REFERENCES public.core_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_drillhole core_drillhole_process_id_e513b27c_fk_core_process_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_drillhole
    ADD CONSTRAINT core_drillhole_process_id_e513b27c_fk_core_process_id FOREIGN KEY (process_id) REFERENCES public.core_process(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_process core_process_organisation_id_b3539040_fk_core_organisation_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_process
    ADD CONSTRAINT core_process_organisation_id_b3539040_fk_core_organisation_id FOREIGN KEY (organisation_id) REFERENCES public.core_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_prospect core_prospect_organisation_id_2033ec0d_fk_core_organisation_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_prospect
    ADD CONSTRAINT core_prospect_organisation_id_2033ec0d_fk_core_organisation_id FOREIGN KEY (organisation_id) REFERENCES public.core_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_prospect core_prospect_process_id_6be9fa7e_fk_core_process_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_prospect
    ADD CONSTRAINT core_prospect_process_id_6be9fa7e_fk_core_process_id FOREIGN KEY (process_id) REFERENCES public.core_process(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_tenement core_tenement_organisation_id_a6e9c1eb_fk_core_organisation_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_tenement
    ADD CONSTRAINT core_tenement_organisation_id_a6e9c1eb_fk_core_organisation_id FOREIGN KEY (organisation_id) REFERENCES public.core_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_tenement core_tenement_process_id_e9ee895b_fk_core_process_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_tenement
    ADD CONSTRAINT core_tenement_process_id_e9ee895b_fk_core_process_id FOREIGN KEY (process_id) REFERENCES public.core_process(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: document_views document_views_document_id_151c5e8f_fk_core_document_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_views
    ADD CONSTRAINT document_views_document_id_151c5e8f_fk_core_document_id FOREIGN KEY (document_id) REFERENCES public.core_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: document_views document_views_user_id_8746d44f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_views
    ADD CONSTRAINT document_views_user_id_8746d44f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profiles user_profiles_organisation_id_6ad56cce_fk_core_organisation_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_organisation_id_6ad56cce_fk_core_organisation_id FOREIGN KEY (organisation_id) REFERENCES public.core_organisation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_profiles user_profiles_user_id_8c5ab5fe_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_8c5ab5fe_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

